
name: Terraform CI CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Init Validate Plan Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/pre_prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ '41f07e27-510a-4f22-a6a4-3f919f6edf45' }}
          tenant-id: ${{ 'e557fe4e-aeeb-4a1c-a74f-ed054a280a9b' }}
          subscription-id: ${{ 'df3f34d4-70dd-49a7-8efb-bce6201171f4' }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -input=false -auto-approve tfplan

